### ISSUE TITLE
TFC server freeze with 1.1236.05.212

### ISSUE THREAD

**Issue by InsaneJ** [MinecraftPortCentral/Cauldron-Issues#107]
For the last couple of weeks we've had an issue on our server that it would sometimes freeze. No apparent crashes, no errors, it just freezes. Any connected client times out and other clients are unable to connect. All that's left to do is to restart the server and hope it doesn't happen again.

The closest thing that might suggest a problem is the following error that happens after the server froze again and we gave it a stop command via console:

```
[22:06:46] [Server console handler/ERROR]: Exception handling console input
java.io.IOException: Input/output error
        at java.io.FileInputStream.readBytes(Native Method) ~[?:1.7.0_71]
        at java.io.FileInputStream.read(FileInputStream.java:272) ~[?:1.7.0_71]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:235) ~[?:1.7.0_71]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:254) ~[?:1.7.0_71]
        at java.io.FilterInputStream.read(FilterInputStream.java:83) ~[?:1.7.0_71]
        at jline.console.ConsoleReader$1.read(ConsoleReader.java:167) ~[ConsoleReader$1.class:?]
        at jline.internal.InputStreamReader.read(InputStreamReader.java:267) ~[InputStreamReader.class:?]
        at jline.internal.InputStreamReader.read(InputStreamReader.java:204) ~[InputStreamReader.class:?]
        at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:995) ~[ConsoleReader.class:?]
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:1167) ~[ConsoleReader.class:?]
        at net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:121) [lv.class:?]
[22:06:46] [Thread-6/INFO]: Stopping server
```

This would suggest the server isn't frozen 100%. Just that clients can't connect for some reason.

Here's the server's log file: http://paste2.org/Z9ckcnw5

We are currently using CauldronInstallerPatch-1.1236.05.212 However the problem also occurs with previous builds all the way back to 1.1217.01.205.

Unfortunately we haven't been able to pin it down so far. Without crash logs or other errors in log files or console it's difficult trying to figure out what's going on. We've tried running the server with only TFC and nothing else, no mods, no plugins. But the result was the same: the server sometimes freezes when players enter (walk/fly) or teleport to certain areas. So far we've been unable to discern a clear pattern and reproduce the freezes reliably.

**Comment by jules103** [comment]
try what ive posted here #112

**Comment by bloodmc** [comment]
@InsaneJ You need to run a profiler such as WarmRoast to find out exactly what is causing the server to freeze up.

If what you say is true about the server ALWAYS locking up after getting the console handler error then find out exactly what command was entered in your server console to reproduce.

**Comment by seriousvern** [comment]
[21:03:10] [Server thread/INFO]: InsaneJ issued server command: /speed 5 
This right here may be your issue. flying that fast on any modded server seems to cause crashes, likely due to the amount of extra data that needs loaded.
