### ISSUE TITLE
1.965.01.205 Exception in server tick loop

### ISSUE THREAD

**Issue by InsaneJ** [MinecraftPortCentral/Cauldron-Issues#110]
Just tried running the new Cauldron 1.965.01.205 for Minecraft 1.6.4 with the HappyDiggers AMP mod pack. Unfortunately it crashes on startup with the following error:

```
java.lang.NoClassDefFoundError: net/minecraftforge/event/ASMEventHandler
    at net.minecraftforge.event.EventBus.register(EventBus.java:77)
    at net.minecraftforge.event.EventBus.register(EventBus.java:58)
    at binnie.core.BinnieCoreMod.<init>(BinnieCoreMod.java:36)
    at binnie.core.BinnieCore.<init>(BinnieCore.java:76)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:200)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:111)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:499)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:94)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:366)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:93)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
```

Here's the full crash report: http://paste2.org/xDOLPGYw
And the ForgeModLoader-server-0.log: http://paste2.org/DIOsNImN

The pack runs well with git-MCPC-Plus-jenkins-Cauldron-164-272.

**Comment by bloodmc** [comment]
Uh you are using the wrong version of MobiusCore/Opis. Update it and everything should be fine.
