### ISSUE TITLE
Deconstruction Table Mod 2.2.5 Error

### ISSUE THREAD

**Issue by Beksim** [MinecraftPortCentral/Cauldron-Issues#111]
I use a mod called Deconstrustion table ( http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288946-1-7-10-1-7-2-1-6-4-1-5-2-forge-deconstruction ) it works fine in forge but not cauldron which leads me to believe it is on cauldrons end. This is every error associated with said mod hopefully you can resolve this issue. Thanks in advance Blood hope to hear from you soon with a fix.

19:54:41] [Thread-11/WARN]:     at deconstruction.deconTable.DeconstructionManager.parseRecipe(DeconstructionManager.java:188)
[19:54:41] [Thread-11/WARN]:    at deconstruction.common.ConfigApplier.run(ConfigApplier.java:12)

9:54:51] [Thread-12/WARN]:  at java.util.ArrayList.rangeCheck(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.get(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:530)
[19:54:51] [Thread-12/WARN]:    at deconstruction.deconTable.DeconRecipe.addShapedOreRecipe(DeconRecipe.java:180)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:38)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:54:51] [Thread-12/ERROR]: Exception Caught: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.rangeCheck(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.get(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:530)
[19:54:51] [Thread-12/WARN]:    at deconstruction.deconTable.DeconRecipe.addShapedOreRecipe(DeconRecipe.java:180)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:38)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:54:51] [Thread-12/ERROR]: Exception Caught: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.rangeCheck(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.get(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:530)
[19:54:51] [Thread-12/WARN]:    at deconstruction.deconTable.DeconRecipe.addShapedOreRecipe(DeconRecipe.java:180)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:38)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:54:51] [Thread-12/ERROR]: Exception Caught: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.rangeCheck(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.get(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:530)
[19:54:51] [Thread-12/WARN]:    at deconstruction.deconTable.DeconRecipe.addShapedOreRecipe(DeconRecipe.java:180)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:38)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:54:51] [Thread-12/ERROR]: Exception Caught: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.rangeCheck(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.get(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:530)
[19:54:51] [Thread-12/WARN]:    at deconstruction.deconTable.DeconRecipe.addShapedOreRecipe(DeconRecipe.java:180)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:38)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:54:51] [Thread-12/ERROR]: Exception Caught: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.rangeCheck(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.get(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:530)
[19:54:51] [Thread-12/WARN]:    at deconstruction.deconTable.DeconRecipe.addShapedOreRecipe(DeconRecipe.java:180)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:38)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:54:51] [Thread-12/ERROR]: Exception Caught: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.rangeCheck(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.get(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:530)
[19:54:51] [Thread-12/WARN]:    at deconstruction.deconTable.DeconRecipe.addShapedOreRecipe(DeconRecipe.java:180)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:38)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:54:51] [Thread-12/ERROR]: Exception Caught: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.rangeCheck(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.get(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:530)
[19:54:51] [Thread-12/WARN]:    at deconstruction.deconTable.DeconRecipe.addShapedOreRecipe(DeconRecipe.java:180)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:38)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:54:51] [Thread-12/ERROR]: Exception Caught: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.rangeCheck(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.get(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:530)
[19:54:51] [Thread-12/WARN]:    at deconstruction.deconTable.DeconRecipe.addShapedOreRecipe(DeconRecipe.java:180)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:38)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:54:51] [Thread-12/ERROR]: Exception Caught: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.rangeCheck(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.get(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:530)
[19:54:51] [Thread-12/WARN]:    at deconstruction.deconTable.DeconRecipe.addShapelessOreRecipe(DeconRecipe.java:210)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:40)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:54:51] [Thread-12/ERROR]: Exception Caught: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.rangeCheck(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.get(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:530)
[19:54:51] [Thread-12/WARN]:    at deconstruction.deconTable.DeconRecipe.addShapelessOreRecipe(DeconRecipe.java:210)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:40)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:54:51] [Thread-12/ERROR]: Exception Caught: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.rangeCheck(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.get(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:530)
[19:54:51] [Thread-12/WARN]:    at deconstruction.deconTable.DeconRecipe.addShapelessOreRecipe(DeconRecipe.java:210)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:40)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:54:51] [Thread-12/ERROR]: Exception Caught: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.rangeCheck(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList.get(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at net.minecraftforge.oredict.OreDictionary$UnmodifiableArrayList.get(OreDictionary.java:530)
[19:54:51] [Thread-12/WARN]:    at deconstruction.deconTable.DeconRecipe.addShapelessOreRecipe(DeconRecipe.java:210)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:40)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)
[19:54:51] [Thread-12/ERROR]: exception caught: java.util.ConcurrentModificationException
[19:54:51] [Thread-12/WARN]: java.util.ConcurrentModificationException
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at java.util.ArrayList$Itr.next(Unknown Source)
[19:54:51] [Thread-12/WARN]:    at deconstruction.common.RecipeMover.run(RecipeMover.java:29)
[19:54:51] [Thread-12/WARN]:    at java.lang.Thread.run(Unknown Source)

**Comment by Beksim** [comment]
I forgot to mention that i am on Cauldron Build 212.
