### ISSUE TITLE
Cauldron bps .210 Launch error

### ISSUE THREAD

**Issue by Menphis88** [MinecraftPortCentral/Cauldron-Issues#117]
My server has been running this setup for 2 weeks or so, and now suddenly after a scheduled restart i get this:

[14:10:17] [main/FATAL]: Failed to start the minecraft server
java.lang.NullPointerException
at org.bukkit.Bukkit.getLogger(Bukkit.java:311) ~[Bukkit.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.210]
at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:185) ~[YamlConfiguration.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.210]
at net.minecraftforge.cauldron.configuration.ConfigBase.<init>(ConfigBase.java:45) ~[ConfigBase.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.210]
at net.minecraftforge.cauldron.configuration.TileEntityConfig.<init>(TileEntityConfig.java:29) ~[TileEntityConfig.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.210]
at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:237) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:69) ~[lt.class:?]
at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1684) [MinecraftServer.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_65]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_65]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [minecraft_server.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.210]
at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [minecraft_server.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.210]

**Comment by jasonjennings** [comment]
Hey, I got this issue on my Pixelmon server all of a sudden too. I started reading into the error and I noticed the area where it said "YamlConfiguration" so I figured it was something to do with yml files. I noticed my cauldron.yml was recently edited so I looked at it and instead of trues it was replaced with some odd numbers, "*id002", so I reset the cauldron.yml and the server started up fine. I know this a old topic and they prob gave up or figured it out but I am doing this just in case someone else has this problem. Not everyone could solve this on their own.

**Comment by cwbit** [comment]
The solution recommended by @jasonjennings worked for us, too.

I just deleted all the `.yml` files in the server root (e.g. where the `cauldron.jar` file was) and the server booted up fine.
