### ISSUE TITLE
My Cauldron server wont start!

### ISSUE THREAD

**Issue by Thundershock27** [MinecraftPortCentral/Cauldron-Issues#133]
I bought a new server of hosthorde and wanted plugins as well as mods. I followed steps given by cauldron and the server hosting client but nothing seems to work.

Console:

05.02 17:44:38 [Multicraft] Server stopped
05.02 17:44:38 [Multicraft] Received stop command
05.02 17:44:10 [Multicraft] Server stopped
05.02 17:44:10 [Multicraft] Server shut down
05.02 17:44:10 [Server] INFO /run.sh: line 31: 17633 Killed                  /monitor.sh "$PID" "$USER"
05.02 17:44:09 [Server] INFO Process 17632 detected
05.02 17:44:09 [Server] INFO Process 17632 dead!
05.02 17:44:09 [Server] INFO ... 14 more
05.02 17:44:09 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:178)
05.02 17:44:09 [Server] INFO Caused by: java.lang.NullPointerException
05.02 17:44:09 [Server] INFO ... 12 more
05.02 17:44:09 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
05.02 17:44:09 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
05.02 17:44:09 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
05.02 17:44:09 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_6_R3.util.ServerShutdownThread
05.02 17:44:09 [Server] INFO ... 6 more
05.02 17:44:09 [Server] INFO at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
05.02 17:44:09 [Server] INFO at net.minecraft.launchwrapper.Launch.launch(Launch.java:128)
05.02 17:44:09 [Server] INFO at java.lang.Class.getMethod(Class.java:1663)
05.02 17:44:09 [Server] INFO at java.lang.Class.getMethod0(Class.java:2813)
05.02 17:44:09 [Server] INFO at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
05.02 17:44:09 [Server] INFO at java.lang.Class.getDeclaredMethods0(Native Method)
05.02 17:44:09 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_6_R3/util/ServerShutdownThread
05.02 17:44:09 [Server] INFO at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
05.02 17:44:09 [Server] INFO at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
05.02 17:44:09 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606)
05.02 17:44:09 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05.02 17:44:09 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
05.02 17:44:09 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05.02 17:44:09 [Server] INFO A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
05.02 17:44:08 [Server] INFO Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
05.02 17:44:08 [Server] INFO Loaded 110 rules from AccessTransformer config file forge_at.cfg
05.02 17:44:08 [Server] INFO Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
05.02 17:44:07 [Server] INFO Loaded 40 rules from AccessTransformer config file fml_at.cfg
05.02 17:44:07 [Server] INFO Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
05.02 17:44:07 [Server] INFO Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
05.02 17:44:07 [Server] INFO Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
05.02 17:44:07 [Server] INFO Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
05.02 17:44:07 [Server] INFO Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
05.02 17:44:07 [Server] INFO Java is OpenJDK 64-Bit Server VM, version 1.7.0_65, running on Linux:amd64:2.6.32-431.29.2.el6.x86_64, installed at /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.65.x86_64/jre
05.02 17:44:07 [Server] INFO Forge Mod Loader version 6.4.49.965 for Minecraft 1.6.4 loading
05.02 17:44:07 [Server] INFO INFO: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
05.02 17:44:07 [Server] INFO Feb 05, 2015 5:44:07 PM net.minecraft.launchwrapper.LogWrapper log
05.02 17:44:07 [Server] INFO INFO: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
05.02 17:44:07 [Server] INFO Feb 05, 2015 5:44:07 PM net.minecraft.launchwrapper.LogWrapper log
05.02 17:44:07 [Server] INFO INFO: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
05.02 17:44:07 [Server] INFO Feb 05, 2015 5:44:07 PM net.minecraft.launchwrapper.LogWrapper log
05.02 17:44:07 [Server] INFO /usr/bin/java $START
05.02 17:44:06 [Multicraft] Loaded config for "Mod: Custom Server"
05.02 17:44:06 [Multicraft] Starting server!
05.02 17:44:06 [Multicraft] Loading server properties
05.02 17:44:06 [Multicraft] Server stopped
05.02 17:44:06 [Multicraft] Retrying server startup
05.02 17:43:36 [Multicraft] Server stopped
05.02 17:43:36 [Multicraft] Server shut down
05.02 17:43:36 [Server] INFO /run.sh: line 31:  9560 Killed                  /monitor.sh "$PID" "$USER"

If anyone knows how to fix this, please help me!!!

Thank you,
Thundershock27

**Comment by MuresanSergiu** [comment]
Are you sure you have installed Cauldron properly?

**Comment by Thundershock27** [comment]
im not sure

**Comment by djoveryde** [comment]
made sure to include the minecraft_server.jar file for the relevant version your trying to load?
