### ISSUE TITLE
/restart throwing error and not restarting

### ISSUE THREAD

**Issue by dezil** [MinecraftPortCentral/Cauldron-Issues#14]
get this error when trying to use /restart

[09:27:12] [Server thread/WARN] [/]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[09:27:12] [Server thread/WARN] [/]:    at cpw.mods.fml.common.asm.transformers.TerminalTransformer$ExitVisitor.checkAccess(TerminalTransformer.java:138)
[09:27:12] [Server thread/WARN] [/]:    at cpw.mods.fml.common.asm.transformers.TerminalTransformer$ExitVisitor.systemExitCalled(TerminalTransformer.java:109)
[09:27:12] [Server thread/WARN] [/]:    at org.spigotmc.RestartCommand.restart(RestartCommand.java:103)
[09:27:12] [Server thread/WARN] [/]:    at org.spigotmc.RestartCommand.execute(RestartCommand.java:25)
[09:27:12] [Server thread/WARN] [/]:    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[09:27:12] [Server thread/WARN] [/]:    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
[09:27:12] [Server thread/WARN] [/]:    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:697)
[09:27:12] [Server thread/WARN] [/]:    at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:465)
[09:27:12] [Server thread/WARN] [/]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:424)
[09:27:12] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[09:27:12] [Server thread/WARN] [/]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[09:27:12] [Server thread/WARN] [/]:    at java.lang.Thread.run(Thread.java:745)

**Comment by bloodmc** [comment]
Caused by FML's new security mechanisms. I'll fix it soon.

**Comment by bloodmc** [comment]
Fixed in build 206.
