### ISSUE TITLE
The server crash everytime i put a bloc.... 

### ISSUE THREAD

**Issue by jagtheboss** [MinecraftPortCentral/Cauldron-Issues#142]
All is said in the tittle. Here is the bug repport... 

---- Minecraft Crash Report ----
// Don't do that.

Time: 10/03/15 23:11
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
    at TMIConfig.isMultiplayer(TMIConfig.java:87)
    at TMIForgeContainer.playerInteract(TMIForgeContainer.java:48)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1_TMIForgeContainer_playerInteract_PlayerInteractEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:51)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:122)
    at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:67)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:423)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:872)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 17 more
Caused by: java.lang.RuntimeException: Attempted to load class bao for invalid side SERVER
    at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:276)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:174)
    ... 19 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8 (x86) version 6.2
    Java Version: 1.8.0_31, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 221176592 bytes (210 MB) / 501088256 bytes (477 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 4 total; -Xms512M -Xmx1024M -XX:+UseParNewGC -XX:+UseConcMarkSweepGC
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.25.1207 Minecraft Forge 10.13.0.1207 17 mods loaded, 17 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.25.1207} [Forge Mod Loader](server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.0.1207} [Minecraft Forge](server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TooManyItems{1.7.10} [TooManyItems](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Trapcraft{v2.2.1a} [Trapcraft]([1.7.10] Trapcraft - v2.3.0a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    carsanddrives{1.0.9} [Cars and Drives](Cars_and_Drives_Mod_V-1.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    dungeonpack{1.7.10-1.0} [Dungeon Pack](dungeonpack-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EasyCrafting{1.7.10-2.0.1.16} [Easy Crafting](EasyCrafting-1.7.10-2.0.1.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    extfar{1.7.10-3.4} [Extended Farming](extfar-1.7.10-3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ftfloocraft{1.7.10-1.1} [Floocraft](Floocraft-1.7.10-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    godweapons{1.5} [God's Weapons](Gods-Weapons-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ninjamod{4.0} [The Ninja Mod](Jond311s-Ninja-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    progressiveautomation{1.4.12} [Progressive Automation](ProgressiveAutomation-1.7.10-1.4.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Roguelike{1.3.6} [Roguelike Dungeons](Roguelike-Dungeons-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SpecialArmor{1.7.10} [TeeLuk's SpecialArmor](TLSpecialArmor-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    weaponmod{1.7.2 v1.14.2} [Balkon's WeaponMod](weaponmod-1.14.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 10; [EntityPlayerMP['Berg'/245, l='world', x=18,92, y=65,43, z=370,11](Berg at 18.919436387102238,65.43349813118775,370.1051144405239)]
    Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Thornbush42** [comment]
Have you put not enough items in the server mods? You're not supposed to

Sent from my Windows Phone

**Comment by jagtheboss** [comment]
Are you saying that i've got too many mods ? How do i know how much i can put ? And they seams to be working, but everytime i put a bloc, the server crashes... I tryed these combination of mods on local first and it works... Maybe some are not in "server format" ... How can i find them to get them out ... I don't really know how to make it work... I tryed to create a server because it don't want to work on lan... I can't join my brother's pc on the same network ...

**Comment by Thornbush42** [comment]
I'm saying that not enough items isn't a server mod and as such should be removed from the server. This is a client-side mod, not server-side.

Sent from my Windows Phone

**Comment by jagtheboss** [comment]
How will it be generating the dungeons and all ninja chests if the server that generates the map don't have the mods ?

**Comment by thormbush42** [comment]
What are you talking about? I'm saying remove the "Not Enough Items" mod, nothing else

**Comment by Thornbush42** [comment]
If you remove the "Too Many Items" mod from the server then it won't crash when placing blocks - This mod is a client-side mod only

PS. If you are still wary about weather you have added other non-server mods then post a list of mods you have installed on the server here.

**Comment by jagtheboss** [comment]
Ah..... ok... i did that, and it worked... I'm stupid =) . Thank you very much... I was about to put it out when my brother told me that it was a server side mod... He was so wrong... Hahahaha Thank you man. Have a nice day...

**Comment by Thornbush42** [comment]
If it's fixed can you please mark this thread as closed, thanks.

Sent from my Windows Phone
