### ISSUE TITLE
Cauldron Crashing

### ISSUE THREAD

**Issue by ghost** [MinecraftPortCentral/Cauldron-Issues#147]
Hello, I have been unable to start up my cauldron server, it crashes on initialization.

fml-server-latest.log:
[15:59:48] [main/INFO] [FML/]: Forge Mod Loader version 7.10.25.1207 for Minecraft 1.7.10 loading
[15:59:49] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_67, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre7
[15:59:51] [main/WARN] [FML/]: The following coremods do not have a @MCVersion annotation. They may cause problems if this is not the correct version of Minecraft for them.
[15:59:51] [main/WARN] [FML/]: Missing @MCVersion: naruto1310.extendedWorkbench.EWFMLPlugin  com.rebelkeithy.dualhotbar.DualHotbarPlugin  redgear.core.asm.CoreLoadingPlugin  
[15:59:51] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:59:51] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[15:59:51] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:59:51] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:59:51] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:51] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[15:59:53] [main/INFO] [LaunchWrapper/]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[15:59:53] [main/INFO] [LaunchWrapper/]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker

latest.log looked extremely similar but here you go anyways:
[15:59:48] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[15:59:48] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[15:59:48] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[15:59:48] [main/INFO]: Forge Mod Loader version 7.10.25.1207 for Minecraft 1.7.10 loading
[15:59:49] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.7.0_67, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre7
[15:59:51] [main/WARN]: The following coremods do not have a @MCVersion annotation. They may cause problems if this is not the correct version of Minecraft for them.
[15:59:51] [main/WARN]: Missing @MCVersion: naruto1310.extendedWorkbench.EWFMLPlugin  com.rebelkeithy.dualhotbar.DualHotbarPlugin  redgear.core.asm.CoreLoadingPlugin  
[15:59:51] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:59:51] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[15:59:51] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:59:51] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:59:51] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:51] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:59:53] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[15:59:53] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[15:59:53] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker

Mod List (All have already been checked that they are 1.7.10:
SecurityCraft
AmberoguiaMod
ExtendedWorkbench
AgravaineLib
AppleCore
BattleTowers
BetterAnvil
BetterSleeping
BetterSugarcane
BiblioCraft
BiblioWoods
BiomesOPlenty
BuildCraft
Call of Duty Knives
Carpenter's Blocks
CharcoalBlock
ChestTransporter
CoroUtil
CustomNPCs
CustomStuff3
DimensionalAnchors
DualHotbar
EnchantingPlus
Extra Achievements
FamiliarsAPI
FamiliarsDefaultMobPack
FamiliarsExtendedFamPack
FamiliarsHerobrineFamPack
FlatSigns
Gravestone
Grim3212 Core
Hammers
Hamsterrific
Hats
iChunUtil
Immibis-Core
InfernalMobs
InfiniteLava
Ladders
LavaBoats
LotsOfFood
Minions
MoarSigns
mobdrops2
MorePeople
MoreCraft
MoreEnchants
MoreFurnaces
MoreMaterials
Morph
MovePlus
Mr. Crayfish's Furniture Mod
Multi Tools
MultiMine
MultiPageChest
NeverMine
RadixCore
SecureCraft
SlabCraft
StairCraft
Sophisticated Wolves
TheCampingMod
TheKitchenMod
ttCore
TTM Ultra Pack
Vanity Blocks
WholeTreeAxe
WorkbenchUpgrades
zz-backpacks

Client Mods (That arent installed on the server)
BetterTitleScreen
DynamicLights
Emotes
InfiniBows
LiteLoader
LinkInfo (LiteLoader Mod)
NoMoreRecipeConflict
NotEnoughItems
OpenEye
Optifine
PlayerAPI
TeamInfo
TimeMod

Any help is greatly appreciated.

**Comment by Thornbush42** [comment]
Have you accepted the EULA in the "eula.txt" file?

Sent from my Windows Phone

**Comment by ghost** [comment]
Yes.

**Comment by ghost** [comment]
Probably should of mentioned that I'm using Maeyanie's cauldron.

**Comment by ghost** [comment]
If it helps, I made the bat file leave the command prompt with the server open, and this showed up when it crashed:

A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Level
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:93)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Level
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 8 more

**Comment by ghost** [comment]
Ok, fixed that issue, now I'm getting this:
A problem occurred running the Server launcher.java.lang.reflect.InvocationTarge
tException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.j
ava:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.
java:12)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPla
yer
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityP
layer
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:188)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more
Caused by: java.lang.NoSuchMethodError: org.objectweb.asm.MethodVisitor.visitMet
hodInsn(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
        at cz.ondraster.bettersleeping.asm.BSTransformer$1$2.visitCode(BSTransfo
rmer.java:52)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at cz.ondraster.bettersleeping.asm.BSTransformer.patchIsDaytime(BSTransf
ormer.java:65)
        at cz.ondraster.bettersleeping.asm.BSTransformer.transform(BSTransformer
.java:11)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchC
lassLoader.java:276)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:174)
        ... 14 more

**Comment by ghost** [comment]
Ok, I fixed the issue.
