### ISSUE TITLE
Crash issue with 1.7.10 cauldron

### ISSUE THREAD

**Issue by ArcLP** [MinecraftPortCentral/Cauldron-Issues#153]
[21:43:13] [Server thread/INFO] [FML/]: Unknown net.minecraftforge.common.chunkio.QueuedChunk {
 x: -35
 z: -173
 loader: null
 world: world
 dimension: 0
 provider: net.minecraft.world.WorldProviderSurface
}
[21:43:13] [Server thread/INFO] [FML/]: This should not happen. Please report this error to Forge.
[21:43:13] [Server thread/INFO] [FML/]: Unknown net.minecraftforge.common.chunkio.QueuedChunk {
 x: -35
 z: -173
 loader: null
 world: world
 dimension: 0
 provider: net.minecraft.world.WorldProviderSurface
}
[21:43:13] [Server thread/INFO] [FML/]: This should not happen. Please report this error to Forge.
[21:43:13] [Server thread/INFO] [FML/]: Unknown net.minecraftforge.common.chunkio.QueuedChunk {
 x: -25
 z: -177
 loader: null
 world: world
 dimension: 0
 provider: net.minecraft.world.WorldProviderSurface
}
[21:43:13] [Server thread/INFO] [FML/]: This should not happen. Please report this error to Forge.
[21:43:13] [Server thread/INFO] [FML/]: Unknown net.minecraftforge.common.chunkio.QueuedChunk {
 x: -25
 z: -177
 loader: null
 world: world
 dimension: 0
 provider: net.minecraft.world.WorldProviderSurface

And

[20:21:58] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.terraingen.PopulateChunkEvent$Pre@66f3b8ed:
net.minecraft.util.ReportedException: Exception getting block type in world
    at net.minecraft.world.World.func_147439_a(World.java:674) ~[ahb.class:?]
    at ivorius.reccomplex.structures.generic.transformers.TransformerNatural.transformBlock(TransformerNatural.java:93) ~[TransformerNatural.class:?]
    at ivorius.reccomplex.structures.generic.transformers.TransformerSingleBlock.transform(TransformerSingleBlock.java:46) ~[TransformerSingleBlock.class:?]
    at ivorius.reccomplex.structures.generic.GenericStructureInfo.generate(GenericStructureInfo.java:150) ~[GenericStructureInfo.class:?]
    at ivorius.reccomplex.structures.generic.GenericStructureInfo.generate(GenericStructureInfo.java:55) ~[GenericStructureInfo.class:?]
    at ivorius.reccomplex.worldgen.StructureGenerator.instantly(StructureGenerator.java:85) ~[StructureGenerator.class:?]
    at ivorius.reccomplex.worldgen.StructureGenerator.randomInstantly(StructureGenerator.java:63) ~[StructureGenerator.class:?]
    at ivorius.reccomplex.worldgen.WorldGenStructures.generate(WorldGenStructures.java:71) ~[WorldGenStructures.class:?]
    at ivorius.reccomplex.events.RCForgeEventHandler.onPreChunkDecoration(RCForgeEventHandler.java:60) ~[RCForgeEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_66_RCForgeEventHandler_onPreChunkDecoration_Pre.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
    at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:377) [aqz.class:?]
    at org.bukkit.craftbukkit.v1_7_R4.generator.NormalChunkGenerator.func_73153_a(NormalChunkGenerator.java:57) [NormalChunkGenerator.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:364) [ms.class:?]
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160) [apx.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62) [ChunkIOProvider.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
    at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) [AsynchronousExecutor$Task.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
    at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) [AsynchronousExecutor.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) [ChunkIOExecutor.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:874) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.NullPointerException
    at com.rikmuld.camping.misc.BoundsStructure$$anonfun$createStructure$1.apply$mcVI$sp(BoundsStructure.scala:59) ~[BoundsStructure$$anonfun$createStructure$1.class:?]
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160) ~[scala-library-2.11.1.jar:?]
    at com.rikmuld.camping.misc.BoundsStructure.createStructure(BoundsStructure.scala:57) ~[BoundsStructure.class:?]
    at com.rikmuld.camping.common.objs.tile.TileEntityTent.setRotation(TileTent.scala:234) ~[TileEntityTent.class:?]
    at com.rikmuld.camping.common.world.CampsiteGeneration.func_76484_a(Structures.scala:39) ~[CampsiteGeneration.class:?]
    at com.rikmuld.camping.common.world.WorldGenerator.generateSurface(WorldGenerator.scala:44) ~[WorldGenerator.class:?]
    at com.rikmuld.camping.common.world.WorldGenerator.generate(WorldGenerator.scala:22) ~[WorldGenerator.class:?]
    at cpw.mods.fml.common.registry.GameRegistry.REPLACED_generateWorld(GameRegistry.java:130) ~[GameRegistry.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
    at sun.reflect.GeneratedMethodAccessor103.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
    at farseek.util.Reflection$MethodValue$.apply$extension(Reflection.scala:51) ~[Reflection$MethodValue$.class:?]
    at farseek.core.ReplacedMethod.apply(MethodReplacementTransformer.scala:132) ~[Farseek-1.0.3.jar:?]
    at farseek.world.gen.ChunkGeneratorExtensions$.generateWorld(ChunkGeneratorExtensions.scala:17) ~[ChunkGeneratorExtensions$.class:?]
    at farseek.world.gen.ChunkGeneratorExtensions.generateWorld(ChunkGeneratorExtensions.scala) ~[ChunkGeneratorExtensions.class:?]
    at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java) ~[GameRegistry.class:git-Cauldron-Reloaded-1.7.10-1.1343.01.0]
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:394) ~[ms.class:?]
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1155) ~[apx.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:249) ~[ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:169) ~[ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137) ~[ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:260) ~[ms.class:?]
    at net.minecraft.world.World.func_72964_e(World.java:739) ~[ahb.class:?]
    at net.minecraft.world.World.func_147439_a(World.java:665) ~[ahb.class:?]
    ... 25 more

Along with other things, it always crashes with this

---- Minecraft Crash Report ----
// My bad.

Time: 12/04/15 20:16
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
    at com.rikmuld.camping.common.objs.block.Tent.func_149749_a(Tent.scala:59)
    at com.rikmuld.camping.common.objs.block.BoundsHelper.func_149749_a(BoundsHelper.scala:40)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:623)
    at net.minecraft.world.World.func_147465_d(World.java:800)
    at net.minecraft.world.gen.feature.WorldGenLakes.func_76484_a(SourceFile:79)
    at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:397)
    at org.bukkit.craftbukkit.v1_7_R4.generator.NormalChunkGenerator.func_73153_a(NormalChunkGenerator.java:57)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:364)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1170)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
    at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
    at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:874)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Terminal-Access** [comment]
Possibly due to one of your mods, if i am reading the log correctly

Caused by: java.lang.NullPointerException
at com.rikmuld.camping.misc.BoundsStructure$$anonfun$createStructure$1.apply$mcVI$sp(BoundsStructure.scala:59) ~[BoundsStructure$$anonfun$createStructure$1.class:?]

Try removing or disabling that mod and trying again.

**Comment by AsylumDreams** [comment]
Oh woops, forgot to close this one.
 I think I worked it out - I'd inadvertently uploaded some 1.8 schematics / chunks  into the 1.7 map.

 Thanks for the reply and suggestions though ^_^

 If you're considering BoundsStructure to be a mod, I've never heard of that :p

**Comment by vico93** [comment]
Cauldron isn't anymore maintained by a central team (used to be bloodmc).
Now some server owners with some java knowledge are updating Cauldron for their own. Some lock the updates for ourselves, while others (benevolents) release that for a guy/girl called 'Yive';
Check its Twitter @ItsYive or here @Yive to ask about his repository and (possibly) for Cauldron updates. This repository is dead.
Sincerely...

**Comment by ArcLP** [comment]
:( those bastards. Thank you very much!

**Comment by ArcLP** [comment]
also looking back at it, the coords, its a corrupted chunk I believe.

**Comment by vico93** [comment]
@ArcLP don't blame bloodmc & co.
Blame the autor of Bukkit's DCMA, Wesley Wolfe (aka wolvereness).
He was the stem of all recent troubles with Bukkit-related projects (Spigot and Cauldron)
