### ISSUE TITLE
AsynchronousExecutor ? Unsure but that seems to be the crux

### ISSUE THREAD

**Issue by AsylumDreams** [MinecraftPortCentral/Cauldron-Issues#154]
Aloha all ^_^

 Hosting a server at Hosthorde, plugins have been stripped down to Essentials / WE / WG and this still happens whenever I enter / approach certain chunks.

 I've just uploaded a map so I'm assuming that something's corrupted but I don't know what would affect across such a broad area.

 Any intel / suggestions would be appreciated,

 Please & Thank you ^_^

Console read-out:

17.04 09:04:18 [Multicraft] Server stopped
17.04 09:04:18 [Multicraft] Server shut down
17.04 09:04:18 [Server] INFO /run.sh: line 31: 11035 Killed                  /monitor.sh "$PID" "$USER"
17.04 09:04:17 [Server] INFO Process 11034 detected
17.04 09:04:17 [Server] INFO Process 11034 dead!
17.04 09:04:16 [Server] INFO The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
17.04 09:04:16 [Server] INFO Holder lookups applied
17.04 09:04:16 [Server] INFO Applying holder lookups
17.04 09:04:16 [Server] INFO Unloading dimension 1
17.04 09:04:16 [Server] INFO Unloading dimension 0
17.04 09:04:16 [Server] INFO Saving chunks for level 'DIM1'/The End
17.04 09:04:16 [Multicraft] Skipped 46 lines due to rate limit (30/s)
17.04 09:04:15 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) ~[AsynchronousExecutor$Task.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
17.04 09:04:15 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) ~[ChunkIOProvider.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
17.04 09:04:15 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44) ~[ChunkIOProvider.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
17.04 09:04:15 [Server] INFO at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:551) ~[aqk.class:?]
17.04 09:04:15 [Server] INFO at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:935) ~[apx.class:?]
17.04 09:04:15 [Server] INFO at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:955) ~[apx.class:?]
17.04 09:04:15 [Server] INFO at net.minecraft.world.chunk.Chunk.func_150810_a(Chunk.java:540) ~[apx.class:?]
17.04 09:04:15 [Server] INFO at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150819_a(ExtendedBlockStorage.java:59) ~[apz.class:?]
17.04 09:04:15 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: -44
17.04 09:04:15 [Server] ERROR Cause of unexpected exception was
17.04 09:04:15 [Server] INFO ... 13 more
17.04 09:04:15 [Server] INFO at net.minecraft.world.chunk.Chunk.func_150810_a(Chunk.java:540) ~[apx.class:?]
17.04 09:04:15 [Server] INFO at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_150819_a(ExtendedBlockStorage.java:59) ~[apz.class:?]
17.04 09:04:15 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: -44
17.04 09:04:15 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
17.04 09:04:15 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
17.04 09:04:15 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?]
17.04 09:04:15 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) ~[lt.class:?]
17.04 09:04:15 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:874) ~[MinecraftServer.class:?]
17.04 09:04:15 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) ~[ChunkIOExecutor.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
17.04 09:04:15 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) ~[AsynchronousExecutor.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
17.04 09:04:15 [Server] INFO at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) ~[AsynchronousExecutor$Task.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
17.04 09:04:15 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) ~[ChunkIOProvider.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
17.04 09:04:15 [Server] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44) ~[ChunkIOProvider.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
17.04 09:04:15 [Server] INFO at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:551) ~[aqk.class:?]
17.04 09:04:15 [Server] INFO at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:935) ~[apx.class:?]
17.04 09:04:15 [Server] INFO at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:955) ~[apx.class:?]
17.04 09:04:15 [Server] INFO at net.minecraft.world.chunk.Chunk.func_150810_a(Chunk.java:554) ~[apx.class:?]
17.04 09:04:15 [Server] INFO net.minecraft.util.ReportedException: Getting block
17.04 09:04:15 [Server] ERROR Encountered an unexpected exception

**Comment by AsylumDreams** [comment]
I think I may have uploaded a schematic from my 1.8 world into it.

 Guessing that that would explain it, their being blocks that can't exist and all ... :p
