### ISSUE TITLE
[URGENT]Server not start

### ISSUE THREAD

**Issue by checkplysgamer** [MinecraftPortCentral/Cauldron-Issues#157]
Im get this error on start my server:

C:\Users\Ricardo\Desktop\Servidor\shthdh>java -XX:PermSize=128m -XX:MaxPermSize=
256m -Xmx1G -Xms1G -jar minecraft_server.jar
A problem occurred running the Server launcher.java.lang.reflect.InvocationTarge
tException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.j
ava:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.
java:12)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:188)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at org.objectweb.asm.ClassVisitor.<init>(Unknown Source)
        at org.objectweb.asm.tree.ClassNode.<init>(Unknown Source)
        at cofh.asm.ASMCore.writeWorld(ASMCore.java:987)
        at cofh.asm.ASMCore.transform(ASMCore.java:177)
        at cofh.asm.CoFHClassTransformer.transform(CoFHClassTransformer.java:38)

        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchC
lassLoader.java:276)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:174)
        ... 14 more

C:\Users\Ricardo\Desktop\Servidor\shthdh>PAUSE
Prima qualquer tecla para continuar . . .

**Comment by Time6628** [comment]
Update the libraries.

**Comment by checkplysgamer** [comment]
Now I have another error:


C:\Users\Ricardo\Desktop\TxCraftModded>java -Xmx512m -Xms512m -XX:MaxPermSize=12
8M -jar caul.jar
Adding Accesstransformer map: CoFH_at.cfg
A problem occurred running the Server launcher.java.lang.reflect.InvocationTarge
tException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.j
ava:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.
java:12)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/WorldServer
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.WorldServer
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:188)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:180)
        ... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:188)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 18 more
Caused by: java.lang.NoSuchMethodError: org.objectweb.asm.tree.MethodInsnNode.<i
nit>(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
        at cofh.asm.ASMCore.writeWorld(ASMCore.java:662)
        at cofh.asm.ASMCore.transform(ASMCore.java:168)
        at cofh.asm.PCCASMTransformer.transform(PCCASMTransformer.java:41)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchC
lassLoader.java:276)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:174)
        ... 20 more

C:\Users\Ricardo\Desktop\TxCraftModded>PAUSE
Prima qualquer tecla para continuar . . .

**Comment by Time6628** [comment]
What version are you using?

**Comment by vpontin** [comment]
@Time6628 , this repository is dead. blood & co. stop to dev Cauldron...
...BUT you can have some suport in https://github.com/gamerforEA/Cauldron-Reloaded or in Yive's Mirror (http://tcpr.ca/)

**Comment by checkplysgamer** [comment]
Im updated to the 1.7.10-2.1403.1.49 and te error stops.
