### ISSUE TITLE
Sender cannot be null (RCON problem)

### ISSUE THREAD

**Issue by Servek** [MinecraftPortCentral/Cauldron-Issues#16]
When I try to send a command by RCON I have an exception. I don't use any plugins and mods

Cauldron version: 1.7.10-1.1217.01.0 (1.1231.01.206 has this issues too)

Logs:
[16:06:49] [Server thread/INFO]: Starting remote control listener
[16:06:49] [RCON Listener #1/INFO]: RCON running on 0.0.0.0:25566
[16:06:49] [Server thread/INFO]: Registered command forge with permission node net.minecraftforge.server.command.ForgeCommand
[16:07:18] [RCON Listener #1/INFO]: Rcon connection from: /127.0.0.1
[16:07:18] [Server thread/WARN]: Unexpected exception while parsing console command "say 1"
java.lang.IllegalArgumentException: Sender cannot be null
    at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[Validate.class:2.6]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:714) ~[CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1217.01.205]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:697) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1217.01.205]
    at net.minecraft.server.MinecraftServer$6.evaluate(MinecraftServer.java:1785) [lm.class:?]
    at net.minecraft.server.MinecraftServer$6.evaluate(MinecraftServer.java:1775) [lm.class:?]
    at org.bukkit.craftbukkit.v1_7_R4.util.Waitable.run(Waitable.java:24) [Waitable.class:git-Cauldron-MCPC-Plus-1.7.10-1.1217.01.205]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:869) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_67]

**Comment by bloodmc** [comment]
Please test build 208.

**Comment by Servek** [comment]
Another exception now. Every command to RCON has same error: "Exception whilst parsing RCON input
java.lang.NullPointerException".

Logs:
[21:34:29] [Server thread/INFO]: Done (6.693s)! For help, type "help" or "?"
[21:34:29] [Server thread/INFO]: Starting remote control listener
[21:34:29] [RCON Listener #1/INFO]: RCON running on locb.su:25591
[21:34:29] [Server thread/INFO]: Registered command forge with permission node net.minecraftforge.server.command.ForgeCommand
[21:34:39] [RCON Listener #1/INFO]: Rcon connection from: /5.9.60.147
[21:34:39] [RCON Client #2/ERROR]: Exception whilst parsing RCON input
java.lang.NullPointerException
    at net.minecraft.network.rcon.RConThreadClient.run(RConThreadClient.java:53) [oz.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_17]
[21:34:40] [RCON Listener #1/INFO]: Rcon connection from: /5.9.60.147
[21:34:40] [RCON Client #3/ERROR]: Exception whilst parsing RCON input
java.lang.NullPointerException
    at net.minecraft.network.rcon.RConThreadClient.run(RConThreadClient.java:53) [oz.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_17]
[21:34:41] [RCON Listener #1/INFO]: Rcon connection from: /5.9.60.147
[21:34:41] [RCON Client #4/ERROR]: Exception whilst parsing RCON input
java.lang.NullPointerException
    at net.minecraft.network.rcon.RConThreadClient.run(RConThreadClient.java:53) [oz.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_17]
[21:34:42] [RCON Listener #1/INFO]: Rcon connection from: /5.9.60.147
[21:34:42] [RCON Client #5/ERROR]: Exception whilst parsing RCON input
java.lang.NullPointerException
    at net.minecraft.network.rcon.RConThreadClient.run(RConThreadClient.java:53) [oz.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_17]
[21:34:43] [RCON Listener #1/INFO]: Rcon connection from: /5.9.60.147
[21:34:43] [RCON Client #6/ERROR]: Exception whilst parsing RCON input
java.lang.NullPointerException
    at net.minecraft.network.rcon.RConThreadClient.run(RConThreadClient.java:53) [oz.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_17]
[21:34:44] [RCON Listener #1/INFO]: Rcon connection from: /5.9.60.147
[21:34:44] [RCON Client #7/ERROR]: Exception whilst parsing RCON input
java.lang.NullPointerException
    at net.minecraft.network.rcon.RConThreadClient.run(RConThreadClient.java:53) [oz.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_17]

**Comment by bloodmc** [comment]
Fixed in build 209.
