### ISSUE TITLE
Cauldron crashes right after launching

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [MinecraftPortCentral/Cauldron-Issues#163]
I am trying to start a modded server using a modpack I created, and I wanted to use plugins as well so I can have Essentials and CoreProtect 2, among others to protect the server. I downloaded Cauldron and followed the steps to set it up. I have not installed any mods or plugins yet, but when I launch the server, the command prompt window opens, stays open for about 5 seconds, then closes. The log file says the following:

---

[17:07:31] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[17:07:32] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[17:07:32] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[17:07:32] [main/INFO]: Forge Mod Loader version 7.10.25.1207 for Minecraft 1.7.10 loading
[17:07:32] [main/INFO]: Java is Java HotSpot(TM) Client VM, version 1.8.0_45, running on Windows 7:x86:6.1, installed at C:\Program Files (x86)\Java\jre1.8.0_45
[17:07:32] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:07:32] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[17:07:32] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:07:32] [main/ERROR]: Unable to launch
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_45]
    at java.util.ArrayList$Itr.remove(Unknown Source) ~[?:1.8.0_45]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:117) [launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [cauldron-1.7.10-1.1207.01.198-server.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [cauldron-1.7.10-1.1207.01.198-server.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]

---

As I don't know Java, I have absolutely no clue what this error means, why it's happening, or how to fix it. Any help would be greatly appreciated!

**Comment by vico93** [comment]
This rep and (of course) Cauldron (official) developement is dead since wolvereness's bukkit DCMA.

BUT, we have a lifeboat: KCauldron: https://gitlab.prok.pw/Prototik/KCauldron
Download the KCauldron build in Yive Mirror (http://tcpr.ca/cauldron). If the issue persists, login and repost the issue in that rep!

**Comment by AwesomeAnimationGamer** [comment]
Thanks! Just one question: Does it work with Spigot plugins? Also, the gitlab link you gave me for KCauldron seems to be broken... I keep timing out when I try to open the link. There are a lot of Cauldron files on the Yive mirror, but none say KCauldron -- are they all KCauldron?

**Comment by vico93** [comment]
Hi, sorry the wrong link to yive mirror. Just go to "Files" menu and a dropdown will appear to correct page. (URL anyway http://tcpr.ca/kcauldron)

About KCauldron: It just a continuation of Cauldron, they will not update to 1.8 due to Sponge (sadly, i prefer Cauldron-like servers anyway, and Sponge seems to be vaporware).
And about the 404 in the repo: its normal. Accordingly to Yive in his twitter, Prototik have issues with your ISP (seems he hosts everything from his house), and sometimes the site goes down.
For info about this you can follow me @vpontin or Yive itself @ItsYive on Twitter for more info about the repo.
