### ISSUE TITLE
InvocationTargetException (NoSuchMethodError)

### ISSUE THREAD

**Issue by midn1** [MinecraftPortCentral/Cauldron-Issues#172]
I've tried using the Cauldron from Maeyanie's website and I've put 39 mods in.
When I start it then immediately an exception is thrown:
`A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.NoSuchMethodError: cpw.mods.fml.common.ModContainerFactory.registerContainerType(Lorg/objectweb/asm/Type;Ljava/lang/Class;)V
        at cofh.asm.LoadingPlugin$CoFHDummyContainer.call(LoadingPlugin.java:244)
        at cofh.asm.LoadingPlugin$CoFHDummyContainer.call(LoadingPlugin.java:204)
        at cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:123)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:114)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more`

**Comment by midn1** [comment]
This happens only when using mods, if there are no mods then it runs fine.
If there's a MissingModsException then this exception is not throwm.

**Comment by vico93** [comment]
For the 1002th time...
This rep and (of course) Cauldron (official) developement is dead since wolvereness's bukkit DCMA.

BUT, we have a lifeboat: KCauldron: https://gitlab.prok.pw/Prototik/KCauldron
Download the KCauldron build in Yive Mirror (http://tcpr.ca/cauldron). If the issue persists, login and repost the issue in that rep!
