### ISSUE TITLE
Server is not starting. (Caused by: com.google.gson.stream.MalformedJsonException:)

### ISSUE THREAD

**Issue by Porkchopseesu2** [MinecraftPortCentral/Cauldron-Issues#173]
PasteBin: http://pastebin.com/h1ZtL33x
ERROR:
[16:52:54] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[16:52:54] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[16:52:54] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[16:52:54] [main/INFO]: Forge Mod Loader version 7.10.85.1236 for Minecraft 1.7.10 loading
[16:52:54] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Linux:amd64:3.14.32-xxxx-grs-ipv6-64, installed at /opt/jre1.8.0_25
[16:52:54] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:52:54] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[16:52:54] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:52:54] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:52:54] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:52:55] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:52:55] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[16:52:56] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[16:52:56] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[16:52:56] [main/INFO]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[16:52:59] [main/FATAL]: Failed to start the minecraft server
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 108973
    at com.google.gson.Gson.assertFullConsumption(Gson.java:779) ~[Gson.class:?]
    at com.google.gson.Gson.fromJson(Gson.java:769) ~[Gson.class:?]
    at net.minecraft.server.management.PlayerProfileCache.func_152657_b(SourceFile:156) ~[ns.class:?]
    at net.minecraft.server.management.PlayerProfileCache.<init>(SourceFile:42) ~[ns.class:?]
    at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:225) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:69) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1684) [MinecraftServer.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [Cauldron.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [Cauldron.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 108973
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
    at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386) ~[JsonReader.class:?]
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:531) ~[JsonReader.class:?]
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:414) ~[JsonReader.class:?]
    at com.google.gson.Gson.assertFullConsumption(Gson.java:775) ~[Gson.class:?]
    ... 18 more

---

After running "java -XX:+UseParallelGC -Xmx12G -jar Cauldron.jar" The server will not start and is throwing that error.

Server:CentOS release 6.7 (Final)
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
Cauldron Version: 1.7.10

**Comment by vico93** [comment]
Cauldron developement is dead. Try to update to its sucessor, Thermos, and if you still run this issue report in its github: https://github.com/CyberdyneCC/Thermos

**Comment by Porkchopseesu2** [comment]
Thank you so much for your help!
