### ISSUE TITLE
Server start failed

### ISSUE THREAD

**Issue by xGabrielUC** [MinecraftPortCentral/Cauldron-Issues#178]
Hello, when I want to open a forge 1.12.2 server in a VPS it shows me the following error

> A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

> 
Forge version: 1.12.2 - 14.23.5.2847
Assigned ram: 3GB (VPS has 12)
Files on the server: https://imgur.com/a/vKMe6Vq

**Comment by JulioCBC13** [comment]
i have the same problem

**Comment by JojocraftTv** [comment]
Try running it with Java 8. 
Forge 1.12.2 only supports up to JDK 8.
Hope this helps :)

If you have more Java version installed on your Server, you can force the server to use a specific version:
`/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx5G -jar forge.jar`

Link for Java 8: `https://www.oracle.com/de/java/technologies/javase/javase-jdk8-downloads.html`
