### ISSUE TITLE
minecraft server problem (Hosting) 1.12.2

### ISSUE THREAD

**Issue by JulioCBC13** [MinecraftPortCentral/Cauldron-Issues#179]
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
13.04 03:55:13 [Server] INFO at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13.04 03:55:13 [Server] INFO at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13.04 03:55:13 [Server] INFO at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13.04 03:55:13 [Server] INFO at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13.04 03:55:13 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
13.04 03:55:13 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
13.04 03:55:13 [Server] INFO Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
13.04 03:55:13 [Server] INFO at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
13.04 03:55:13 [Server] INFO at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
13.04 03:55:13 [Server] INFO ... 6 more

plis help me

**Comment by DieGamingDullis** [comment]
The old Forge Versions doesn't work anymore! Pls upgrade to an newer version. (1.14.4 or 1.16.5)

**Comment by JojocraftTv** [comment]
Try running it with Java 8. 
Forge 1.12.2 only supports up to JDK 8.
Hope this helps :)

If you have more Java version installed on your Server, you can force the server to use a specific version:
`/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx5G -jar forge.jar`

Link for Java 8: `https://www.oracle.com/de/java/technologies/javase/javase-jdk8-downloads.html`
