### ISSUE TITLE
problem with server launcher.java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by iliane442** [MinecraftPortCentral/Cauldron-Issues#182]
Hello everyone ;
i've tried everything that is said on this topic, but i still get the same error.
Can someone help me?

The error :
"sudo java -jar forge-1.12.2-14.23.5.2855.jar
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
"
I can't find java 8 anymore...

_Originally posted by @Wolfsprit in https://github.com/MinecraftPortCentral/Cauldron-Issues/issues/26#issuecomment-819782122_

**Comment by JojocraftTv** [comment]
Try running it with Java 8. 
Forge 1.12.2 only supports up to JDK 8.
Hope this helps :)
