### ISSUE TITLE
Twilight Forest Crashes and Hangs

### ISSUE THREAD

**Issue by ylluminate** [MinecraftPortCentral/Cauldron-Issues#23]
Interesting occurrence when using Twilight Forest.  Mod seems to work great, but while it is hunting for a good spawn point, it kicks everyone off the server.  Not a huge deal, but it seems that `cauldron` needs to handle the lag / delay somehow better.

**Comment by ylluminate** [comment]
Ran into another more serious crash with TwilightForest that recurs regularly with `twilightforest.TFEventListener.entityHurts` (seems to happen regularly with the `hydra` entity:

```
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 10/19/14 12:03 AM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_70056_a(DDDFFI)V
    at twilightforest.TFEventListener.entityHurts(TFEventListener.java:408)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_41_TFEventListener_entityHurts_LivingHurtEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:139)
    at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:287)
    at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1285)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:901)
    at twilightforest.entity.boss.EntityTFHydra.superAttackFrom(EntityTFHydra.java:915)
    at twilightforest.entity.boss.EntityTFHydra.func_70965_a(EntityTFHydra.java:910)
    at net.minecraft.entity.boss.EntityDragonPart.func_70097_a(SourceFile:39)
    at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:313)
    at net.minecraft.world.World.func_72866_a(World.java:2648)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
    at net.minecraft.world.World.func_72870_g(World.java:2601)
    at net.minecraft.world.World.func_72939_s(World.java:2413)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at twilightforest.TFEventListener.entityHurts(TFEventListener.java:408)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_41_TFEventListener_entityHurts_LivingHurtEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:139)
    at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:287)
    at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1285)
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:901)
    at twilightforest.entity.boss.EntityTFHydra.superAttackFrom(EntityTFHydra.java:915)
    at twilightforest.entity.boss.EntityTFHydra.func_70965_a(EntityTFHydra.java:910)
    at net.minecraft.entity.boss.EntityDragonPart.func_70097_a(SourceFile:39)
    at net.minecraft.entity.projectile.EntityArrow.func_70071_h_(EntityArrow.java:313)
    at net.minecraft.world.World.func_72866_a(World.java:2648)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
    at net.minecraft.world.World.func_72870_g(World.java:2601)

-- Entity being ticked --
Details:
    Entity Type: Arrow (net.minecraft.entity.projectile.EntityArrow)
    Entity ID: 110532
    Entity Name: arrow
    Entity's Exact location: 1008.09, 37.44, -947.79
    Entity's Block location: World: (1008,37,-948), Chunk: (at 0,2,12 in 63,-60; contains blocks 1008,0,-960 to 1023,255,-945), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
    Entity's Momentum: -0.00, -0.05, 0.00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2413)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
    Level name: DIM7
    All players: 5 total; [EntityPlayerMP['legend_prime'/87649, l='DIM7', x=1006.50, y=31.00, z=-948.50](legend_prime at 1006.5,31.0,-948.5), EntityPlayerMP['ylluminate'/87844, l='DIM7', x=1025.77, y=38.04, z=-949.01](ylluminate at 1025.7699467632845,38.04374282899225,-949.0096785039441), EntityPlayerMP['Xanthara'/88854, l='DIM7', x=1014.59, y=40.38, z=-962.28](Xanthara at 1014.5856791635853,40.38046680785936,-962.2757186934393), EntityPlayerMP['ylluminarious'/88859, l='DIM7', x=1019.94, y=36.74, z=-961.54](ylluminarious at 1019.9381247347795,36.73941602216553,-961.5413968272493), EntityPlayerMP['beanie_prime'/87725, l='DIM7', x=1009.48, y=36.17, z=-956.17](beanie_prime at 1009.4785460558336,36.165048334029265,-956.1719850405613)]
    Chunk stats: ServerChunkCache: 525 Drop: 0
    Level seed: 4007276668508678788
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (0,33,0), Chunk: (at 0,2,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 23018795 game time, 23018795 day time
    Level dimension: 7
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 8026 (now: true), thunder time: 47161 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.8.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1938847152 bytes (1849 MB) / 2406744064 bytes (2295 MB) up to 2406744064 bytes (2295 MB)
    JVM Flags: 12 total; -Xmn2G -Xss4M -Xmx2500M -XX:+UseLargePages -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+UseBiasedLocking -Xincgc -XX:MaxGCPauseMillis=10 -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:+CMSParallelRemarkEnabled -XX:ParallelGCThreads=10
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 27802, allocated: 12, tallocated: 96
    FML: MCP v9.05 FML v7.10.84.1217 Minecraft Forge 10.13.1.1217 18 mods loaded, 18 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.84.1217} [Forge Mod Loader] (cauldron.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.1.1217} [Minecraft Forge] (cauldron.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.14} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FloatingRuins{1.7.10.r01} [FloatingRuins] ([1.7.10]FloatingRuins-universal-1.7.10.r01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Treecapitator{1.7.2} [Treecapitator] ([1.7.2]Treecapitator-universal-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{6.0.18} [BuildCraft] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{6.0.18} [BC Builders] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{6.0.18} [BC Energy] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{6.0.18} [BC Factory] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{6.0.18} [BC Transport] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{6.0.18} [BC Silicon] (buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MoCreatures{6.3.0} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.0-2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_Minions{1.9.4} [Minions] (Minions-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 5 / 20; [EntityPlayerMP['legend_prime'/87649, l='DIM7', x=1006.50, y=31.00, z=-948.50](legend_prime at 1006.5,31.0,-948.5), EntityPlayerMP['ylluminate'/87844, l='DIM7', x=1025.77, y=38.04, z=-949.01](ylluminate at 1025.7699467632845,38.04374282899225,-949.0096785039441), EntityPlayerMP['Xanthara'/88854, l='DIM7', x=1014.59, y=40.38, z=-962.28](Xanthara at 1014.5856791635853,40.38046680785936,-962.2757186934393), EntityPlayerMP['ylluminarious'/88859, l='DIM7', x=1019.94, y=36.74, z=-961.54](ylluminarious at 1019.9381247347795,36.73941602216553,-961.5413968272493), EntityPlayerMP['beanie_prime'/87725, l='DIM7', x=1009.48, y=36.17, z=-956.17](beanie_prime at 1009.4785460558336,36.165048334029265,-956.1719850405613)]
    Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)
```

**Comment by ylluminate** [comment]
Have also seen that using the magic bean also reliably crashes the server.

**Comment by bloodmc** [comment]
MD: bll/a (DDDFFI)V net/minecraft/client/entity/EntityOtherPlayerMP/func_70056_a (DDDFFI)V

TF problem calling client method on server.
