### ISSUE TITLE
/restart does not work from ingame (works fine from console)

### ISSUE THREAD

**Issue by dezil** [MinecraftPortCentral/Cauldron-Issues#34]
[10:09:34 INFO]: Attempting to restart with ./restart.sh
[10:09:34 INFO]: dezil_nz lost connection: Server is restarting

[10:09:34 WARN](java.util.ConcurrentModificationException):        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at java.util.ArrayList$Itr.next(ArrayList.java:831)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at org.spigotmc.RestartCommand.execute(RestartCommand.java:25)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1348)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1130)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[10:09:34 WARN](java.util.ConcurrentModificationException):        at java.lang.Thread.run(Thread.java:745)

**Comment by dezil** [comment]
an update on this issue the error happens if any player is connected to the server

**Comment by bloodmc** [comment]
you need to post the COMPLETE log.

**Comment by dezil** [comment]
there is nothing else to post apart from the 16000 lines of my server loading the server kicks all connections when the /restart is issued but does not restart the server and anyatempt by players to connect results in a kick

**Comment by bloodmc** [comment]
@dezil do what I said and upload the entire server log then post the link.

**Comment by dezil** [comment]
https://www.dropbox.com/s/tdeuebm0efn7x1k/fml-server-3.txt?dl=0
found i could reconnect so the /restart was ran 2 times from in-game then from console to actually restart the server

**Comment by EkoJR** [comment]
Having the same issue, and seems like a rather high priority to have other admins and staff have the ability to restart.

http://pastebin.com/46WqU79n

**Comment by 0zlw** [comment]
Post removed: Information was incorrect

**Comment by 0zlw** [comment]
Yeah, the error occurs only when players are connected
