### ISSUE TITLE
AE2 - Player crash 

### ISSUE THREAD

**Issue by cauliflower69** [MinecraftPortCentral/Cauldron-Issues#36]
[12:34:43] [Server thread/ERROR]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ServerCustomPacketEvent@743e8e9b:
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleStatisticsIncrease(CraftEventFactory.java:952) ~[CraftEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at net.minecraft.stats.StatFileWriter.func_150871_b(StatFileWriter.java:31) ~[pq.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_71064_a(EntityPlayerMP.java:1139) ~[mw.class:?]
    at appeng.core.stats.Stats.addToPlayer(Stats.java:37) ~[Stats.class:?]
    at appeng.util.Platform.poweredInsert(Platform.java:1394) ~[Platform.class:?]
    at appeng.container.AEBaseContainer.shiftStoreItem(AEBaseContainer.java:694) ~[AEBaseContainer.class:?]
    at appeng.container.AEBaseContainer.func_82846_b(AEBaseContainer.java:359) ~[AEBaseContainer.class:?]
    at appeng.container.AEBaseContainer.doAction(AEBaseContainer.java:788) ~[AEBaseContainer.class:?]
    at appeng.core.sync.packets.PacketInventoryAction.serverPacketData(PacketInventoryAction.java:74) ~[PacketInventoryAction.class:?]
    at appeng.core.sync.network.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:26) ~[AppEngServerPacketHandler.class:?]
    at appeng.core.sync.network.NetworkHandler.serverPacket(NetworkHandler.java:78) ~[NetworkHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_559_NetworkHandler_serverPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) [FMLEventChannel.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) [NetworkEventFiringHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) [NetworkEventFiringHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
[12:34:43] [Server thread/ERROR]: Index: 1 Listeners:
[12:34:43] [Server thread/ERROR]: 0: NORMAL
[12:34:43] [Server thread/ERROR]: 1: ASM: appeng.core.sync.network.NetworkHandler@2d199c6d serverPacket(Lcpw/mods/fml/common/network/FMLNetworkEvent$ServerCustomPacketEvent;)V
[12:34:43] [Server thread/ERROR]: NetworkEventFiringHandler exception
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleStatisticsIncrease(CraftEventFactory.java:952) ~[CraftEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at net.minecraft.stats.StatFileWriter.func_150871_b(StatFileWriter.java:31) ~[pq.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_71064_a(EntityPlayerMP.java:1139) ~[mw.class:?]
    at appeng.core.stats.Stats.addToPlayer(Stats.java:37) ~[Stats.class:?]
    at appeng.util.Platform.poweredInsert(Platform.java:1394) ~[Platform.class:?]
    at appeng.container.AEBaseContainer.shiftStoreItem(AEBaseContainer.java:694) ~[AEBaseContainer.class:?]
    at appeng.container.AEBaseContainer.func_82846_b(AEBaseContainer.java:359) ~[AEBaseContainer.class:?]
    at appeng.container.AEBaseContainer.doAction(AEBaseContainer.java:788) ~[AEBaseContainer.class:?]
    at appeng.core.sync.packets.PacketInventoryAction.serverPacketData(PacketInventoryAction.java:74) ~[PacketInventoryAction.class:?]
    at appeng.core.sync.network.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:26) ~[AppEngServerPacketHandler.class:?]
    at appeng.core.sync.network.NetworkHandler.serverPacket(NetworkHandler.java:78) ~[NetworkHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_559_NetworkHandler_serverPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
[12:34:43] [Server thread/ERROR]: There was a critical exception handling a packet on channel AE2
java.lang.NullPointerException
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleStatisticsIncrease(CraftEventFactory.java:952) ~[CraftEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at net.minecraft.stats.StatFileWriter.func_150871_b(StatFileWriter.java:31) ~[pq.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_71064_a(EntityPlayerMP.java:1139) ~[mw.class:?]
    at appeng.core.stats.Stats.addToPlayer(Stats.java:37) ~[Stats.class:?]
    at appeng.util.Platform.poweredInsert(Platform.java:1394) ~[Platform.class:?]
    at appeng.container.AEBaseContainer.shiftStoreItem(AEBaseContainer.java:694) ~[AEBaseContainer.class:?]
    at appeng.container.AEBaseContainer.func_82846_b(AEBaseContainer.java:359) ~[AEBaseContainer.class:?]
    at appeng.container.AEBaseContainer.doAction(AEBaseContainer.java:788) ~[AEBaseContainer.class:?]
    at appeng.core.sync.packets.PacketInventoryAction.serverPacketData(PacketInventoryAction.java:74) ~[PacketInventoryAction.class:?]
    at appeng.core.sync.network.AppEngServerPacketHandler.onPacketData(AppEngServerPacketHandler.java:26) ~[AppEngServerPacketHandler.class:?]
    at appeng.core.sync.network.NetworkHandler.serverPacket(NetworkHandler.java:78) ~[NetworkHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_559_NetworkHandler_serverPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.01.208]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
[12:34:43] [Server thread/INFO]: flawlzz lost connection: A fatal error has occured, this connection is terminated
[12:34:43] [Server thread/INFO]: flawlzz left the game.

**Comment by bloodmc** [comment]
Fixed in commit https://github.com/MinecraftPortCentral/mcpc-mvn-repo/commit/927d32c05a08eb6f590612c07b32b61f7e58b226

Wipe your libraries folder and rerun the installer to get latest API.

**Comment by sharkck** [comment]
Will using the 206 installer install the libraries needed to fix this problem?

**Comment by sharkck** [comment]
Indeed it did!
