### ISSUE TITLE
java.lang.NoSuchMethodError: org.bukkit.craftbukkit.v1_7_R4.block.CraftBlockState.<init>(Lnet/minecraftforge/common/util/BlockSnapshot;)V

### ISSUE THREAD

**Issue by BrainStone** [MinecraftPortCentral/Cauldron-Issues#44]
Shortly after the server starts I get this crash:

```
[20:52:37 ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:937) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_67]
Caused by: java.lang.NoSuchMethodError: org.bukkit.craftbukkit.v1_7_R4.block.CraftBlockState.<init>(Lnet/minecraftforge/common/util/BlockSnapshot;)V
        at net.minecraft.block.BlockSapling.func_149674_a(BlockSapling.java:71) ~[anj.class:?]
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:562) ~[mt.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:276) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920) ~[MinecraftServer.class:?]
        ... 4 more
```

This happens with 1.1231.01.207 and 1.1231.01.208

**Comment by BrainStone** [comment]
I overread that you had to delete the libraries folder...
