### ISSUE TITLE
Cauldron will not start, even without mods/plugins cauldron wont start.

### ISSUE THREAD

**Issue by jev217** [MinecraftPortCentral/Cauldron-Issues#54]
When i run the run.bat this is what i get this:

C:\Users\bob\Desktop\GoF sever test>title run-minecraft

C:\Users\bob\Desktop\GoF sever test>path=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDO
WS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x
86)\Windows Live\Shared;\"Program Files"\Java\jre7\bin

C:\Users\bob\Desktop\GoF sever test>java.exe -Xms1048M -Xmx2048M -jar cauldron-1
.7.10-1.1207.01.198-server.jar nogui
A problem occurred running the Server launcher.java.lang.reflect.InvocationTarge
tException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.j
ava:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.
java:12)
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_7_R4/util/S
erverShutdownThread
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_7_R4.util
.ServerShutdownThread
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:188)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 12 more
Caused by: java.lang.NullPointerException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at cpw.mods.fml.common.asm.transformers.TerminalTransformer.transform(Te
rminalTransformer.java:14)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchC
lassLoader.java:276)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLo
ader.java:174)
        ... 14 more

C:\Users\bob\Desktop\GoF sever test>PAUSE
Press any key to continue . . .

I most times can find a crash report somewhere but when this happens a crash report isnt made for some reason.

**Comment by bloodmc** [comment]
Follow directions on website and update to latest build 209.
