### ISSUE TITLE
com.google.gson.JsonSyntaxException At start up

### ISSUE THREAD

**Issue by prodkid** [MinecraftPortCentral/Cauldron-Issues#55]
The server won't start up. Here is the log
http://pastebin.com/jE2ZxCqp

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 8194
    at com.google.gson.internal.Streams.parse(Streams.java:56) ~[Streams.class:?]
    at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:54) ~[TreeTypeAdapter.class:?]
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[TypeAdapterRuntimeTypeWrapper.class:?]
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81) ~[CollectionTypeAdapterFactory$Adapter.class:?]
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) ~[CollectionTypeAdapterFactory$Adapter.class:?]
    at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
    at com.google.gson.Gson.fromJson(Gson.java:768) ~[Gson.class:?]
    at net.minecraft.server.management.PlayerProfileCache.func_152657_b(SourceFile:156) ~[ns.class:?]
    at net.minecraft.server.management.PlayerProfileCache.<init>(SourceFile:42) ~[ns.class:?]
    at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:225) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.<init>(DedicatedServer.java:69) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1684) [MinecraftServer.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_65]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_65]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [cauldron.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
    at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [cauldron.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 8194
    at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:519) ~[JsonReader.class:?]
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:414) ~[JsonReader.class:?]
    at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:644) ~[TypeAdapters$25.class:?]
    at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:667) ~[TypeAdapters$25.class:?]
    at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642) ~[TypeAdapters$25.class:?]
    at com.google.gson.internal.Streams.parse(Streams.java:44) ~[Streams.class:?]
    ... 23 more

**Comment by prodkid** [comment]
hm, somehow one of my .json got modified and caused it not to start.
