### ISSUE TITLE
It just crashes when i try to start it up. mcpc-plus-1.6.4-R2.1-forge965-B251.jar

### ISSUE THREAD

**Issue by FilleDev** [MinecraftPortCentral/Cauldron-Issues#6]
Crash log: java.lang.NoClassDefFoundError: scala/collection/Seq
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.ILanguageAdapter$ScalaAdapter.getNewInstance(ILanguageAdapter.java:21)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:518)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:350)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:92)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)
Caused by: java.lang.ClassNotFoundException: scala.collection.Seq
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 30 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 16499881480 bytes (15735 MB) / 20580925440 bytes (19627 MB) up to 20580925440 bytes (19627 MB)
    JVM Flags: 3 total; -Xms20G -Xmx20G -XX:PermSize=128m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport:
java.lang.NullPointerException
    at org.bukkit.Bukkit.getName(Bukkit.java:72)
    at org.bukkit.craftbukkit.v1_6_R3.CraftCrashReport.call(CraftCrashReport.java:19)
    at net.minecraft.crash.CrashReportCategory.func_71500_a(CrashReportCategory.java:106)
    at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:58)
    at net.minecraft.crash.CrashReport.<init>(CrashReport.java:40)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:689)
    at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

```
FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 75 mods loaded, 75 mods active
mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
FML{6.4.49.965} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed
Forge{9.11.1.965} [Minecraft Forge] (modpack.jar) Unloaded->Constructed
AppliedEnergistics-Core{rv14.finale3} [AppliedEnergistics Core] (minecraft.jar) Unloaded->Constructed
CodeChickenCore{0.9.0.9} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed
NotEnoughItems{1.6.1.9} [Not Enough Items] (NotEnoughItems 1.6.1.9.jar) Unloaded->Constructed
CoFHCore{2.0.0.5} [CoFH Core] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed
ForgeMultipart{1.0.1.268} [Forge Multipart] (ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed
BuildCraft|Core{4.2.2} [BuildCraft] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
ThermalExpansion{3.0.0.7} [Thermal Expansion] (ThermalExpansion-3.0.0.7.jar) Unloaded->Constructed
IC2{2.0.397-experimental} [IndustrialCraft 2] (industrialcraft-2_2.0.397-experimental.jar) Unloaded->Constructed
AdvancedSolarPanel{3.4.7} [Advanced Solar Panels] (AdvancedSolarPanels_3_4_7_IC_EXP.zip) Unloaded->Constructed
AppliedEnergistics{rv14.finale3} [Applied Energistics] (appeng-rv14-finale3-mc16x.jar) Unloaded->Constructed
Autoutils{1.0.1} [Autoutils] (autoutils-1.6.4-1.0.1.jar) Unloaded->Constructed
Backpack{1.28.37} [Backpack] (backpack-1.28.37-1.6.x.jar) Unloaded->Constructed
BiblioCraft{1.5.5} [BiblioCraft] (BiblioCraft[v1.5.5].zip) Unloaded->Constructed
BuildCraft|Builders{4.2.2} [BC Builders] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
BuildCraft|Energy{4.2.2} [BC Energy] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
BuildCraft|Factory{4.2.2} [BC Factory] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
BuildCraft|Transport{4.2.2} [BC Transport] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
BuildCraft|Silicon{4.2.2} [BC Silicon] (buildcraft-A-1.6.4-4.2.2.jar) Unloaded->Constructed
CarpentersBlocks{3.2.7} [Carpenter's Blocks] (Carpenter's Blocks v3.2.7 - MC 1.6.4.zip) Unloaded->Constructed
Chisel{1.5.0} [Chisel] (chisel-1.6.4-1.5.0fix.jar) Unloaded->Constructed
CoFHLoot{2.0.0.5} [CoFH Loot] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed
CoFHMasquerade{2.0.0.5} [CoFH Masquerade] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed
CoFHSocial{2.0.0.5} [CoFH Social] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed
CoFHWorld{2.0.0.5} [CoFH World] (CoFHCore-2.0.0.5.jar) Unloaded->Constructed
ComputerCraft{1.63} [ComputerCraft] (ComputerCraft1.63.jar) Unloaded->Constructed
DungeonPack{1.6.4} [DungeonPack] (DungeonPack 1.6.4.zip) Unloaded->Constructed
EnderStorage{1.4.3.6} [EnderStorage] (EnderStorage 1.4.3.6.jar) Unloaded->Constructed
ExtrabiomesXL{3.15.8} [ExtrabiomesXL] (ExtrabiomesXL-universal-1.6.4-3.15.8.jar) Unloaded->Constructed
factorization{0.8.34} [Factorization] (Factorization-0.8.34.jar) Unloaded->Constructed
factorization.misc{0.8.34} [Factorization Miscellaneous Nonsense] (Factorization-0.8.34.jar) Unloaded->Constructed
factorization.notify{0.8.34} [Factorization Notification System] (Factorization-0.8.34.jar) Unloaded->Constructed
factorization.dimensionalSlice{0.8.34} [Factorization Dimensional Slices] (Factorization-0.8.34.jar) Unloaded->Constructed
FlansMod{4.1.1} [Flans Mod] (FlansMod-4.1.1.jar) Unloaded->Constructed
Forestry{2.3.1.1} [Forestry for Minecraft] (forestry-A-2.3.1.1.jar) Unloaded->Constructed
GalacticraftCore{2.0.14} [Galacticraft Core] (Galacticraft-1.6.4-2.0.14.1084.jar) Unloaded->Constructed
GalacticraftMars{2.0.14} [Galacticraft Mars] (Galacticraft-Planets-1.6.4-2.0.14.1084.jar) Unloaded->Constructed
IC2Fixes{1.0} [IC2 Fixes] (IC2Fixes.jar) Unloaded->Constructed
IC2LaserFix{1.0} [IC2 Laser Fix] (IC2LaserFix-2.0.jar) Unloaded->Constructed
ImmibisCore{57.2.0} [Immibis Core] (immibis-core-57.2.0.jar) Unloaded->Constructed
inventorytweaks{1.56} [Inventory Tweaks] (InventoryTweaks-MC1.6.2-1.56-b77.jar) Unloaded->Constructed
IronChest{5.4.1.702} [Iron Chest] (ironchest-universal-1.6.4-5.4.1.702.zip) Unloaded->Constructed
KeithyUtils{1.3} [Keithy Utils] (KeithyUtils-1.6.4-1.3.30.jar) Unloaded->Constructed
LogisticsPipes|Main{0.7.4.dev.294} [Logistics Pipes] (LogisticsPipes-MC1.6.4-0.7.4.dev.294.jar) Unloaded->Constructed
mcheli{0.9.3} [MC Helicopter] (mcheli) Unloaded->Constructed
Mekanism{6.0.5} [Mekanism] (Mekanism-6.0.5.46.jar) Unloaded->Constructed
MekanismGenerators{6.0.5} [MekanismGenerators] (MekanismGenerators-6.0.5.46.jar) Unloaded->Constructed
MekanismTools{6.0.5} [MekanismTools] (MekanismTools-6.0.5.46.jar) Unloaded->Constructed
cfm{3.3.4} [MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.3.4(1.6.4).jar) Unloaded->Constructed
NEIAddons{1.10.5.70} [NEI Addons] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
NEIAddons|AE{1.10.5.70} [NEI Addons: Applied Energistics] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
NEIAddons|MiscPeripherals{1.10.5.70} [NEI Addons: Misc Peripherals] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
NEIAddons|ExtraBees{1.10.5.70} [NEI Addons: Extra Bees] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
NEIAddons|Forestry{1.10.5.70} [NEI Addons: Forestry] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
NEIAddons|CraftingTables{1.10.5.70} [NEI Addons: Crafting Tables] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
NEIAddons|ExNihilo{1.10.5.70} [NEI Addons: Ex Nihilo] (neiaddons-mc164-1.10.5.70.jar) Unloaded->Constructed
NEIPlugins{1.1.0.6} [NEI Plugins] (NEIPlugins-1.1.0.6.jar) Unloaded->Constructed
ProjRed|Core{4.3.7.32} [ProjectRed] (ProjectRedBase-1.6.4-4.3.7.32.jar) Unloaded->Constructed
ProjRed|Integration{4.3.7.32} [ProjectRed-Integration] (ProjectRedIntegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed
ProjRed|Transmission{4.3.7.32} [ProjectRed-Transmission] (ProjectRedIntegration-1.6.4-4.3.7.32.jar) Unloaded->Constructed
ProjectZulu|Core{1.1.7.3} [Project Zulu Core] (ProjectZuluCompletev1.1.7.3.zip) Unloaded->Constructed
ProjectZulu|Block{1.1.7.3} [Project Zulu Block and Items] (ProjectZuluCompletev1.1.7.3.zip) Unloaded->Constructed
ProjectZulu|Dungeon{1.1.7.3} [Project Zulu Dungeon] (ProjectZuluCompletev1.1.7.3.zip) Unloaded->Constructed
ProjectZulu|Mob{1.1.7.3} [Project Zulu Mobs] (ProjectZuluCompletev1.1.7.3.zip) Unloaded->Constructed
ProjectZulu|World{1.1.7.3} [Project Zulu World] (ProjectZuluCompletev1.1.7.3.zip) Unloaded->Constructed
Railcraft{8.4.0.0} [Railcraft] (Railcraft_1.6.4-8.4.0.0.jar) Unloaded->Constructed
Statues{2.1.1} [Statues] (statues-1.6.4-2.1.1.jar) Unloaded->Constructed
Tubestuff{57.1.3} [Tubestuff] (tubestuff-57.1.3.jar) Unloaded->Constructed
TwilightForest{1.20.4} [The Twilight Forest] (twilightforest-1.6.4-1.20.4.jar) Unloaded->Constructed
taverns{2.1.6-3} [Village Taverns] (VillageTaverns-2.1.6-3.15.jar) Unloaded->Constructed
McMultipart{1.0.1.268} [Minecraft Multipart Plugin] (ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded->Constructed
ForgeMicroblock{1.0.1.268} [Forge Microblocks] (ForgeMultipart-universal-1.6.4-1.0.1.268.jar) Unloaded
Profiler Position: N/A (disabled)
Is Modded: Definitely; Server brand changed to 'mcpc,craftbukkit,fml,forge'
Type: Dedicated Server (map_server.txt)
```

**Comment by bloodmc** [comment]
MCPC not supported, update to Cauldron.

**Comment by FilleDev** [comment]
I downloaded this from the cauldron website
