### ISSUE TITLE
Rcon problem - 208 / 209 versions

### ISSUE THREAD

**Issue by inside002** [MinecraftPortCentral/Cauldron-Issues#80]
hello, i make a 208/209 version on latest build who "make" a solution but this is not working.

In 208 version i have error like this (when i sent command from site donateshop with command "say text"):

[12:21:38 INFO]: Rcon connection from: /XX.XXX.XXX.XXX.XXX
[12:21:38 ERROR]: Exception whilst parsing RCON input
java.lang.NullPointerException
        at net.minecraft.network.rcon.RConThreadClient.run(RConThreadClient.java:53) [oz.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]

In 209 version i have similar error like in 207, the same command:

[11:30:35 INFO]: Rcon connection from: /XXX.XXX.XXX.XXX
[11:30:35 WARN]: Unexpected exception while parsing console command "say Test"
java.lang.IllegalArgumentException: Sender cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[Validate.class:2.6]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:714) ~[CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:697) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
        at net.minecraft.server.MinecraftServer$6.evaluate(MinecraftServer.java:1785) [lm.class:?]
        at net.minecraft.server.MinecraftServer$6.evaluate(MinecraftServer.java:1775) [lm.class:?]
        at org.bukkit.craftbukkit.v1_7_R4.util.Waitable.run(Waitable.java:24) [Waitable.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:869) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]

Any solutions?

**Comment by lanord** [comment]
Got the same trouble using mcrcon (https://github.com/Tiiffi/mcrcon) on Mac OS X (10.10)

[13:50:07 INFO]: Rcon connection from: /redacted :P
[13:50:07 WARN]: Unexpected exception while parsing console command "list"
java.lang.IllegalArgumentException: Sender cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[Validate.class:2.6]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:714) ~[CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:697) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
        at net.minecraft.server.MinecraftServer$6.evaluate(MinecraftServer.java:1785) [lm.class:?]
        at net.minecraft.server.MinecraftServer$6.evaluate(MinecraftServer.java:1775) [lm.class:?]
        at org.bukkit.craftbukkit.v1_7_R4.util.Waitable.run(Waitable.java:24) [Waitable.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:869) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]

**Comment by inside002** [comment]
:(

**Comment by Servek** [comment]
+Fix, please

**Comment by inside002** [comment]
Blood, pls fix it! :)

**Comment by ghost** [comment]
Fix please

**Comment by bloodmc** [comment]
Fixed in build 210
