### ISSUE TITLE
IC2 spam

### ISSUE THREAD

**Issue by linkinkov** [MinecraftPortCentral/Cauldron-Issues#91]
[20:31:31] [Server thread/WARN]: java.util.concurrent.ExecutionException: java.lang.RuntimeException: incompatible matrix
[20:31:31] [Server thread/WARN]: at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[20:31:31] [Server thread/WARN]: at java.util.concurrent.FutureTask.get(FutureTask.java:188)
[20:31:31] [Server thread/WARN]: at ic2.core.energy.Grid.finishCalculation(Grid.java:360)
[20:31:31] [Server thread/WARN]: at ic2.core.energy.EnergyNetLocal.onTickEnd(EnergyNetLocal.java:359)
[20:31:31] [Server thread/WARN]: at ic2.core.energy.EnergyNetGlobal.onTickEnd(EnergyNetGlobal.java:68)
[20:31:31] [Server thread/WARN]: at ic2.core.TickHandler.onWorldTick(TickHandler.java:77)
[20:31:31] [Server thread/WARN]: at cpw.mods.fml.common.eventhandler.ASMEventHandler_7_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
[20:31:31] [Server thread/WARN]: at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[20:31:31] [Server thread/WARN]: at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[20:31:31] [Server thread/WARN]: at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:260)
[20:31:31] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
[20:31:31] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
[20:31:31] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[20:31:31] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[20:31:31] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)
[20:31:31] [Server thread/WARN]: Caused by: java.lang.RuntimeException: incompatible matrix
[20:31:31] [Server thread/WARN]: at ic2.core.energy.Grid.calculateDistribution(Grid.java:472)
[20:31:31] [Server thread/WARN]: at ic2.core.energy.Grid.calculate(Grid.java:417)
[20:31:31] [Server thread/WARN]: at ic2.core.energy.GridCalculation.call(GridCalculation.java:12)
[20:31:31] [Server thread/WARN]: at ic2.core.energy.GridCalculation.call(GridCalculation.java:5)
[20:31:31] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[20:31:31] [Server thread/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[20:31:31] [Server thread/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[20:31:31] [Server thread/WARN]: ... 1 more
[20:31:31] [Server thread/INFO]: Grid 4136 info:
[20:31:31] [Server thread/INFO]: 63 nodes
[20:31:31] [Server thread/INFO]: 1
[20:31:31] [Server thread/INFO]: entries in cache, hitrate
[20:31:31] [Server thread/INFO]: 100.00
[20:31:31] [Server thread/INFO]: %
[20:31:31] [Server thread/INFO]: Matrices unavailable

This messages spam everysecond. For 24 hour online have log file - 132mb

**Comment by linkinkov** [comment]
How possible disable it?
